import { useEffect, useRef, useState } from 'react';

// A single generation turn can now produce several messages (one per
// character plus narration, SPEC.md 3.8), each broadcast as its own
// message_complete event. The raw token stream is shown as one growing
// "generating..." blob until generation_done, at which point the caller
// refetches the session to render the properly parsed, per-character bubbles.
export function useChatStream(sessionId, onGenerationDone) {
  const [streamingText, setStreamingText] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [sceneChangeNotice, setSceneChangeNotice] = useState(null);
  const onDoneRef = useRef(onGenerationDone);
  onDoneRef.current = onGenerationDone;

  useEffect(() => {
    if (sessionId == null) return undefined;

    const protocol = location.protocol === 'https:' ? 'wss:' : 'ws:';
    const ws = new WebSocket(`${protocol}//${location.host}/ws?roomSessionId=${sessionId}`);

    ws.onmessage = (event) => {
      const data = JSON.parse(event.data);
      if (data.type === 'generation_start') {
        setIsGenerating(true);
        setStreamingText('');
        setError(null);
      } else if (data.type === 'token') {
        setStreamingText((prev) => prev + data.token);
      } else if (data.type === 'scene_change_detected') {
        setSceneChangeNotice(data.description);
      } else if (data.type === 'generation_done') {
        setIsGenerating(false);
        setStreamingText('');
        onDoneRef.current?.();
      } else if (data.type === 'message_complete') {
        // Scene images are generated by a queue that runs after generation_done
        // already fired, so a late image message needs its own refetch trigger.
        onDoneRef.current?.();
      } else if (data.type === 'error') {
        setIsGenerating(false);
        setStreamingText('');
        setError(data.message);
      }
    };

    return () => ws.close();
  }, [sessionId]);

  return { streamingText, isGenerating, error, sceneChangeNotice };
}
