import { api } from './client.js';

export const settingsApi = {
  status: () => api.get('/settings/status'),
  startKoboldcpp: () => api.post('/settings/start-koboldcpp'),
  getKoboldcppLaunchSettings: () => api.get('/settings/koboldcpp-launch-settings'),
  updateKoboldcppLaunchSettings: (data) => api.put('/settings/koboldcpp-launch-settings', data),
  getKoboldcppModelFiles: () => api.get('/settings/koboldcpp-model-files'),
  getLlmGenerationSettings: () => api.get('/settings/llm-generation-settings'),
  updateLlmGenerationSettings: (data) => api.put('/settings/llm-generation-settings', data),
  getChatInputSettings: () => api.get('/settings/chat-input-settings'),
  updateChatInputSettings: (data) => api.put('/settings/chat-input-settings', data),
  listStylePresets: () => api.get('/settings/style-presets'),
  createStylePreset: (data) => api.post('/settings/style-presets', data),
  updateStylePreset: (id, data) => api.put(`/settings/style-presets/${id}`, data),
  removeStylePreset: (id) => api.del(`/settings/style-presets/${id}`),
  listImageFormats: () => api.get('/settings/image-formats'),
  setImageFormat: (kind, format) => api.put(`/settings/image-formats/${kind}`, { format }),
  listSamplers: () => api.get('/settings/samplers'),
  listImageGenerationSettings: () => api.get('/settings/image-generation-settings'),
  updateImageGenerationSettings: (kind, data) => api.put(`/settings/image-generation-settings/${kind}`, data),
  testGenerateImageGenerationSettings: (kind, data) => api.post(`/settings/image-generation-settings/${kind}/test-generate`, data),
  testGenerateImage: (data) => api.post('/settings/test-generate-image', data),
  getStatusDisplayPreferences: () => api.get('/settings/status-display-preferences'),
  updateStatusDisplayPreferences: (data) => api.put('/settings/status-display-preferences', data),
};
